-- Actualizar tabla combos
ALTER TABLE combos
ADD COLUMN IF NOT EXISTS descripcion VARCHAR(500) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS esta_activo BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS ultima_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- Actualizar tabla ventas
ALTER TABLE ventas
ADD COLUMN IF NOT EXISTS cliente VARCHAR(100) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS observaciones VARCHAR(500),
ADD COLUMN IF NOT EXISTS fecha_venta TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- Actualizar tabla combo_detalles
ALTER TABLE combo_detalles
ADD COLUMN IF NOT EXISTS cantidad_libras DECIMAL(18,2) NOT NULL DEFAULT 0; 